#ifndef RCGE_IO_H
#define RCGE_IO_H

#include <rcge/rcge_window.h>
#include <stdbool.h>

char *rcge_io_read_file_all(char *path, int buffer_size);

typedef enum
{
    IO_KEY_SPACE = 0,
    IO_KEY_APOSTROPHE,
    IO_KEY_COMMA,
    IO_KEY_MINUS,
    IO_KEY_PERIOD,
    IO_KEY_SLASH,
    IO_KEY_0,
    IO_KEY_1,
    IO_KEY_2,
    IO_KEY_3,
    IO_KEY_4,
    IO_KEY_5,
    IO_KEY_6,
    IO_KEY_7,
    IO_KEY_8,
    IO_KEY_9,
    IO_KEY_SEMICOLON,
    IO_KEY_EQUAL,
    IO_KEY_A,
    IO_KEY_B,
    IO_KEY_C,
    IO_KEY_D,
    IO_KEY_E,
    IO_KEY_F,
    IO_KEY_G,
    IO_KEY_H,
    IO_KEY_I,
    IO_KEY_J,
    IO_KEY_K,
    IO_KEY_L,
    IO_KEY_M,
    IO_KEY_N,
    IO_KEY_O,
    IO_KEY_P,
    IO_KEY_Q,
    IO_KEY_R,
    IO_KEY_S,
    IO_KEY_T,
    IO_KEY_U,
    IO_KEY_V,
    IO_KEY_W,
    IO_KEY_X,
    IO_KEY_Y,
    IO_KEY_Z,
    IO_KEY_LEFT_BRACKET,
    IO_KEY_BACKSLASH,
    IO_KEY_RIGHT_BRACKET,
    IO_KEY_GRAVE_ACCENT,
    IO_KEY_WORLD_1,
    IO_KEY_WORLD_2,
    IO_KEY_ESCAPE,
    IO_KEY_ENTER,
    IO_KEY_TAB,
    IO_KEY_BACKSPACE,
    IO_KEY_INSERT,
    IO_KEY_DELETE,
    IO_KEY_RIGHT,
    IO_KEY_LEFT,
    IO_KEY_DOWN,
    IO_KEY_UP,
    IO_KEY_PAGE_UP,
    IO_KEY_PAGE_DOWN,
    IO_KEY_HOME,
    IO_KEY_END,
    IO_KEY_CAPS_LOCK,
    IO_KEY_SCROLL_LOCK,
    IO_KEY_NUM_LOCK,
    IO_KEY_PRINT_SCREEN,
    IO_KEY_PAUSE,
    IO_KEY_F1,
    IO_KEY_F2,
    IO_KEY_F3,
    IO_KEY_F4,
    IO_KEY_F5,
    IO_KEY_F6,
    IO_KEY_F7,
    IO_KEY_F8,
    IO_KEY_F9,
    IO_KEY_F10,
    IO_KEY_F11,
    IO_KEY_F12,
    IO_KEY_F13,
    IO_KEY_F14,
    IO_KEY_F15,
    IO_KEY_F16,
    IO_KEY_F17,
    IO_KEY_F18,
    IO_KEY_F19,
    IO_KEY_F20,
    IO_KEY_F21,
    IO_KEY_F22,
    IO_KEY_F23,
    IO_KEY_F24,
    IO_KEY_F25,
    IO_KEY_KP_0,
    IO_KEY_KP_1,
    IO_KEY_KP_2,
    IO_KEY_KP_3,
    IO_KEY_KP_4,
    IO_KEY_KP_5,
    IO_KEY_KP_6,
    IO_KEY_KP_7,
    IO_KEY_KP_8,
    IO_KEY_KP_9,
    IO_KEY_KP_DECIMAL,
    IO_KEY_KP_DIVIDE,
    IO_KEY_KP_MULTIPLY,
    IO_KEY_KP_SUBTRACT,
    IO_KEY_KP_ADD,
    IO_KEY_KP_ENTER,
    IO_KEY_KP_EQUAL,
    IO_KEY_LEFT_SHIFT,
    IO_KEY_LEFT_CONTROL,
    IO_KEY_LEFT_ALT,
    IO_KEY_LEFT_SUPER,
    IO_KEY_RIGHT_SHIFT,
    IO_KEY_RIGHT_CONTROL,
    IO_KEY_RIGHT_ALT,
    IO_KEY_RIGHT_SUPER,
    IO_KEY_MENU,
    IO_KEY_LAST,

    IO_MOUSE_1, //121
    IO_MOUSE_2,
    IO_MOUSE_3,
    IO_MOUSE_4,
    IO_MOUSE_5,
    IO_MOUSE_6,
    IO_MOUSE_7,
    IO_MOUSE_8,
    IO_MOUSE_LAST,
    IO_MOUSE_LEFT,
    IO_MOUSE_RIGHT,
    IO_MOUSE_MIDDLE
} rcge_io_input;

#define RCGE_IO_KEY_THRESHOLD 0
#define RCGE_IO_MOUSE_THRESHOLD 121

typedef enum
{
    IO_TYPE_KEYBOARD,
    IO_TYPE_MOUSE
} rcge_io_input_type;

rcge_io_input_type rcge_io_input_type_get(rcge_io_input input);
bool rcge_io_input_pressed(rcge_window window, rcge_io_input input);
void rcge_io_mouse_loc(rcge_window window, double* x, double* y);

#endif