#ifndef RCGE_DATATYPE_H
#define RCGE_DATATYPE_H

typedef enum {
    DATATYPE_BYTE,
    DATATYPE_UNSIGNED_BYTE,
    DATATYPE_SHORT,
    DATATYPE_UNSIGNED_SHORT,
    DATATYPE_INT,
    DATATYPE_UNSIGNED_INT,
    DATATYPE_FLOAT,
    DATATYPE_DOUBLE,
    DATATYPE_HALF_FLOAT,
    DATATYPE_INT_2_10_10_10_REV,
    DATATYPE_UNSIGNED_INT_2_10_10_10_REV,
    DATATYPE_BOOL 
} rcge_datatype;

#endif